{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [                            
    clang
    gnumake
    autoconf 
    automake 
    pkgconfig 
    libtool 
    cmake 
    vim
    rsync     
    wget   
    curl
    unzip
    p7zip
    git
    xfce.terminal
    nmap
    telnet
    #hping
    xchat
    tor
    gnupg 
    openconnect 
    firefox
    #icecat3
    python
    pidgin
    docker
    nodePackages.npm
    nodePackages.npm2nix
    nodePackages.express
    nodePackages.selenium-webdriver
    nodePackages.statsd
    nixops
    linuxPackages.virtualbox
    #linuxPackages_3_17.virtualbox
    thunderbird
    sl
    kde4.kcalc
    linuxPackages.virtualbox
    powertop
    latencytop
    redshift
    nfsUtils
    s6Dns
  ];  

}
